name: percy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  build_and_test:
    name: Compilation du site Hugo et test avec Percy
    runs-on: ubuntu-latest
    steps:

    - name: Récupération des données
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Installation de Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Installation des dépendances JavaScript
      run: yarn install

    - name: Installation de Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: 'latest'
        extended: true

    - name: Compilation du site
      run: yarn osuny percy-build

    - run: npm install --save-dev @percy/cli
    - run: npx percy snapshot snapshots.yml
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}